### ISSUE TITLE
[FR] files & folders view

### ISSUE THREAD

**Issue by ildar** [iamSahdeep/Bop#15]
I like the feature list. Though one big feature is missing: files & folders view/playback

**Comment by iamSahdeep** [comment]
Yes, will soon add it, probably in next release. However i have currently provided an intent to open supportable audio files though device file manager.

**Comment by iamSahdeep** [comment]
Done, check the latest release https://github.com/iamSahdeep/Bop/releases/tag/v1.1 
However there are some bugs due to dependency on MediaStore like if the file is not in mediastore it wont play it, working on it too :(

**Comment by ildar** [comment]
Kinda useless. I can play just one file, not the whole folder
Reopen?

**Comment by iamSahdeep** [comment]
Alright, will try to Add this tooo. 😊

**Comment by iamSahdeep** [comment]
Hey @ildar i have added this feature with temporary UI, if you could confirm if its working as expected i would update the beta version asap. 
here is the apk : https://github.com/iamSahdeep/Bop/blob/master/buildApk/app-debug.apk

**Comment by ildar** [comment]
Sorry, couldn't test when you requested: got desperately busy. Will test it
anyway
