### ISSUE TITLE
"Play all" button in All-Songs section

### ISSUE THREAD

**Issue by bikebastler** [iamSahdeep/Bop#20]
I would like to request a "Play all" button in the All-Songs section.
Currently I have to create a Playlist with all songs for this and recreate this playlist every time I add a song.

**Comment by iamSahdeep** [comment]
That FAB provided in the Allsongs section is for playing all songs there in that list or in mediastore😀. Please report if its not working as required.Also create more issues for more feature request if any.😊

**Comment by bikebastler** [comment]
Thats a pitty^^
Seems like I was a bit blind yesterday. :-D works like a charm.
