### ISSUE TITLE
Immediate crashing

### ISSUE THREAD

**Issue by Novaaaaaaaa** [iamSahdeep/Bop#21]
Upon opening the app it immediately crashes. I've cleared all data, and have even reinstalled the app, but the app still crashes. I'm using version 1.1 beta on a Galaxy S7 Edge running 8.0.0. Because I can't enter the app, nor am I rooted, I cannot provide any logs.

**Comment by iamSahdeep** [comment]
I have found the possible problem. It may be happening, if any of the artist, genre, albums or playlist have 0 songs in it. I will try to remove the genres etc. if there is no songs in it.

**Comment by iamSahdeep** [comment]
@Novaaaaaaaa can you plz check if this apk is working or not. Here is the apk : https://github.com/iamSahdeep/Bop/blob/master/buildApk/app-debug.apk

**Comment by Novaaaaaaaa** [comment]
@iamSahdeep works, thanks!

**Comment by iamSahdeep** [comment]
Thank you, I will update the app soon.
