### ISSUE TITLE
Find bugs in the application when accessing equalizer settings in landscape mode

### ISSUE THREAD

**Issue by riyandacountri88** [iamSahdeep/Bop#24]
Name: Access equalizer settings in landscape mode
Recommended 'bug': Finds an error when accessing the set equalizer in landscape mode.

#### To reproduce the steps to reproduce behavior:
- Go to 'Register your song center'
![k1](https://user-images.githubusercontent.com/47910767/53282753-f05bf780-376e-11e9-9e36-a6e564ab975d.png)

- Click on the song you want to play & click on the cover of the song. then click the settings icon placed in the upper right corner to go to the Equalizer settings. when compiling is in the settings section. The equalizer reverses the position of your screen in landscape mode, then the application stops and restarts on its own.
![k3](https://user-images.githubusercontent.com/47910767/53282762-010c6d80-376f-11e9-8b58-fc8a41fbf4ca.png)
![k4](https://user-images.githubusercontent.com/47910767/53282768-0f5a8980-376f-11e9-8ffe-cea09ab31375.png)
![k5](https://user-images.githubusercontent.com/47910767/53282772-1d100f00-376f-11e9-9ea8-8db696c7f055.png)

https://youtu.be/LgP6KNZf3R0

#### See expected errors and behavior Supposedly
Supposedly, compiling into "Equalizer Settings" in the "Landscape Mode" application will not stop and be re-presented by itself. Because the Equalizer is more easily accessed with "Landscape Mode".

#### Tool:
Device: [OPPO F5]
Processor: [Eight Core]
[Android 7.1.1] version

**Comment by riyandacountri88** [comment]
Hi sir, if I design a new logo for your application, will you be happy and
give permission or you can use it if you like? if you want I will try to
design a minimalist logo, thank you sir.

Pada tanggal Min, 24 Feb 2019 01.26, Sahdeep Singh <notifications@github.com>
menulis:

**Comment by riyandacountri88** [comment]
Thank you sir

Pada tanggal Min, 24 Feb 2019 01.29, Sahdeep Singh <notifications@github.com>
menulis:

**Comment by iamSahdeep** [comment]
Hey @riyandacountri88 i have resolved it, you can download the apk from here : https://github.com/iamSahdeep/Bop/blob/master/buildApk/app-debug.apk  and check it on your device too. Although it was just one line of code :)

**Comment by iamSahdeep** [comment]
Hello @riyandacountri88 i didn't look your previous comments before, and thanks for offering new logo design. It would be great if you can directly contact me on my email : sahdeepsingh98@gmail.com

**Comment by riyandacountri88** [comment]
With pleasure, I will definitely contact you sir. Thank you!
