### ISSUE TITLE
[FR] remove notification after timeout

### ISSUE THREAD

**Issue by ildar** [iamSahdeep/Bop#26]
It hangs for a few days already paused. Is not right. AFAIK other players have this timeout equals to ~5 minutes

**Comment by iamSahdeep** [comment]
Can you please elaborate, I can't quite understand. You saying notification doesn't close?

**Comment by ildar** [comment]
Should go away automatically after a timeout (say of 5 min) if player isn't
playing (paused or stopped)

**Comment by iamSahdeep** [comment]
Well notification should remove itself if the song is stopped, tell me if its not removing. And for the pausing the player, its up to the user to remove the notification after pausing, for that I have provided the cancel option to remove the notification.
Also if timeout is required i will try to implement it too.

**Comment by iamSahdeep** [comment]
Hey @ildar i have added the 5 min timeout now. Actually i didn't realise that some manufactures doesn't support custom UI for notification. Also i have now switch to mediastyle notification and with time out. You can also text apk if you want to https://github.com/iamSahdeep/Bop/blob/master/buildApk/app-debug.apk

If it doesn't work as expected please report again. Thanks :1st_place_medal:
