### ISSUE TITLE
Report on application for new logo design

### ISSUE THREAD

**Issue by riyandacountri88** [iamSahdeep/Bop#28]
![sampul](https://user-images.githubusercontent.com/47910767/53701157-d97f6a00-3e2c-11e9-8013-c065e76a872d.png)

Hi, I have prepared all the files for you and I have sent them via email, this is my report about the design request via an email that you agreed to a few days ago. Thank you for giving me a chance, I will smile if my logo is useful and you can use it on the Bop-Music Player application.

#### Idea
I tried to enter the first letter of the application name (Bop-Music Player) which is the letter "b" in this logo design and tried to insert a mix of play music icons in the middle of the letter "b" so that the application's character was clearer, I did not remove the initial color character the application but I chose a slightly darker color to make it look more sweet and simple.

![ide](https://user-images.githubusercontent.com/47910767/53701185-1186ad00-3e2d-11e9-8a3e-af5288b352c3.png)

![pembatas](https://user-images.githubusercontent.com/47910767/53701191-1d726f00-3e2d-11e9-9b1c-a5211a9908e9.png)

![variant logo up](https://user-images.githubusercontent.com/47910767/53701196-2b27f480-3e2d-11e9-9966-f461ab9c073d.png)

![gradient up](https://user-images.githubusercontent.com/47910767/53701202-34b15c80-3e2d-11e9-84dc-5aebf9d6b96f.png)

![pembatas](https://user-images.githubusercontent.com/47910767/53701191-1d726f00-3e2d-11e9-9b1c-a5211a9908e9.png)

![size up](https://user-images.githubusercontent.com/47910767/53701219-4b57b380-3e2d-11e9-9dc9-d0185a41ba40.png)

![pembatas](https://user-images.githubusercontent.com/47910767/53701191-1d726f00-3e2d-11e9-9b1c-a5211a9908e9.png)

![font up](https://user-images.githubusercontent.com/47910767/53715965-057b0980-3e86-11e9-8c70-06e6ad1eaa24.png)

![pembatas](https://user-images.githubusercontent.com/47910767/53701191-1d726f00-3e2d-11e9-9b1c-a5211a9908e9.png)

![procces](https://user-images.githubusercontent.com/47910767/53701233-7c37e880-3e2d-11e9-9dc2-a2f85b2dd3b5.png)

![pembatas](https://user-images.githubusercontent.com/47910767/53701191-1d726f00-3e2d-11e9-9b1c-a5211a9908e9.png)

![main logo 02](https://user-images.githubusercontent.com/47910767/53715986-1592e900-3e86-11e9-8d9b-a66caf03b151.png)

![pembatas](https://user-images.githubusercontent.com/47910767/53701191-1d726f00-3e2d-11e9-9b1c-a5211a9908e9.png)

![main logo 03](https://user-images.githubusercontent.com/47910767/53716010-25123200-3e86-11e9-807e-3ae8ef8a0b61.png)

![mockup](https://user-images.githubusercontent.com/47910767/53701247-8f4ab880-3e2d-11e9-902f-0fd99141cb6d.png)

#### Benefit
Benefits / Improvements
For the benefit of Bop-MusicPlayer logo are:

![main logo](https://user-images.githubusercontent.com/47910767/53701252-9a9de400-3e2d-11e9-8981-6e31fdbce77c.png)

- Character applications more prominent.
- Sweet and simple and not overdone.
- logo visually easy to understand.
- A logo made in context-based gridlines. aim for proportional.
- Logo created with the concept of responsive and highly context. Here symbolizes that the brand should make design aesthetics and have an understanding in a different context so that the design can be applied to posters, business cards, and more.

#### Tool.
I made the Bop-MusicPlayer Logo using CDRx7. And I provide vector files (SVG, PDF, EPS and PSD) for flexibility and scalability, as well as the .PNG file format for immediate use of the design.

#### Original File.
[All Files](https://drive.google.com/drive/folders/1GWidUlDJOwqsLvsfiHzE1V4Swx-5XrGl?usp=sharing)

#### Address that can be contacted
riyandacountri@gmail.com
yandaofficial88@gmail.com

I am waiting for your reply with a smile :)

**Comment by iamSahdeep** [comment]
Thank you @riyandacountri88 for this awesome logo. The design and everything is perfect and looks fab.

Thank you again 😊

**Comment by riyandacountri88** [comment]
Thank you sir, if you need a fresher design in the future. You can contact me via email.

**Comment by iamSahdeep** [comment]
Surely 😊
