### ISSUE TITLE
Control Bop via Bluetooth-Headset

### ISSUE THREAD

**Issue by bikebastler** [iamSahdeep/Bop#29]
Hi there,
to control the playback via my bluetooth headset would be nice.
currently it don't do anything if I press the buttons on my headset.
Other music apps on my androidphone (Galaxy A3 2017 8.0 stock) recognize the headset.

**Comment by iamSahdeep** [comment]
Hello @bikebastler I have just updated the application with these features. Now it is supporting bluetooth  button events. There might be issue in headshook event ( double click on play/pause button) but it  works fine with some all the devices i tested upon. You can also text the latest apk : https://github.com/iamSahdeep/Bop/blob/master/buildApk/app-debug.apk 
And report me here if thing doesn't work as expected.

**Comment by bikebastler** [comment]
@iamSahdeep 
Its working fine in the apk-debug app :+1: 
Thanks for your work!
