### ISSUE TITLE
Add FAQs

### ISSUE THREAD

**Issue by HarryHeights** [iamSahdeep/Bop#30]
Hi! I'm Harry. I've read reviews about your app. I decided to give it a try, It's great. I like the style or the user interface rather. Been using the app for some days now. It has the potential to become my daily driver music player. 
I'd love to contribute by creating FAQs document for the app. It's my way of saying I appreciate your work and efforts. 
What do you think about this?

**Comment by iamSahdeep** [comment]
Hello @HarryHeights , thanks for +ve feedback and for FAQs documents, it would be great. I do really appreciate any kind of contribution. You are more than the welcome to contribute. You can create and update me with PR whenever its ready. If you have questions regarding content you can contact me at my email : sahdeepsingh98@gmail.com .

**Comment by HarryHeights** [comment]
Alright thanks for granting permission. I'll work on it right away
