### ISSUE TITLE
Playlist don't show immediately after it is created. Until I exit the app and launch again.

### ISSUE THREAD

**Issue by HarryHeights** [iamSahdeep/Bop#31]
**Describe the bug**
After I created a playlist, I accessed the playlist tab and I didn't see any of the created playlists there.  They would only show when I exit the app and re-launch

**To Reproduce**
1. Go to the "songs" page
2. Highlight songs you wish to add to a playlist
3. Create playlist
4. Access the playlist page
5. See error. (It shows empty playlist)

**Expected behavior**
I expected that after I had created a playlist, I would see the playlist on the designated page and be able to use it. 

**Screen recording**
https://youtu.be/b3vBhc--WXc

**Test Environment**
 - Device: Redmi Note 5 Pro
 - OS: Android 8.1
 - Software version: Bop music player v1.1.2

**Comment by iamSahdeep** [comment]
Hey @HarryHeights  , will work on it asap.

**Comment by HarryHeights** [comment]
Okay. That's great. I'm still working on the FAQs. Would be done soon.

**Comment by iamSahdeep** [comment]
@HarryHeights ,I have added swipe to refresh layout to refresh the playlists list. Will soon update in releases

**Comment by HarryHeights** [comment]
Oh okay. That's great
