### ISSUE TITLE
Ability to edit playlist.

### ISSUE THREAD

**Issue by HarryHeights** [iamSahdeep/Bop#32]
**Is your feature request related to a problem? Please describe.**
It's not quite a problem but maybe it is. I can't edit playlists on the app. 

**Describe the solution you'd like**
The edit icon on a playlist can only be used to edit a playlist name. It'd be great if when I click the edit option I'd be able to edit both playlist name and contents of the playlist.
- I'd be able to remove or add songs to the playlist. 

**Describe alternatives you've considered**
There's no other alternative

**Comment by iamSahdeep** [comment]
Will work on it too, but would take some. Actually i was thinking to change some logic in playlist creation and displaying list first, before playing. Will look possibilities and update soon.

**Comment by HarryHeights** [comment]
Oh okay. I'm optimistic about how this change will be implemented. Keep up the good work

**Comment by iamSahdeep** [comment]
fixed in v1.2.1
