### ISSUE TITLE
Bop music player crashed after i removed a song and click on next/previous button

### ISSUE THREAD

**Issue by sagorahmed** [iamSahdeep/Bop#36]
**Describe the bug**
The crash happens after I removed a playing/running song from all songs folder and clicked on the track changer previous/next button. 

**To Reproduce**
1. Launch the app and go to "All Songs" folder.
2. Click on a song (The song will start to play)
3. Tap on ⋮ (Three dots/ Vertical ellipsis) and remove that song (You will notice the song is started to play again from the beginning).
5. Then tap on music logo. 
6. Then click on track changer next or previous button.
4. Finally, See error.

**Expected behavior**
I expected that after removing the song it will stop to play or the player will move to another song. I think this not weird than freezing the app by taping on the next/previous button. I expected the app will run smoothly after I clicked on that button.

**Screen Recording**
Here is my phone's recorded video of that bug
https://www.youtube.com/watch?v=xKMk8Nqa9jQ

**Smartphone (please complete the following information):**
 - Device: Samsung A5
 - OS: Android 6.0.1
 - App version: Bop music player v1.2

**Additional context**
Here are all errors that made this app freeze/crash.
```
03-20 17:46:02.202 22305 22305 E AndroidRuntime: FATAL EXCEPTION: main

03-20 17:46:02.202 22305 22305 E AndroidRuntime: Process: com.sahdeepsingh.Bop, PID: 22305

03-20 17:46:02.202 22305 22305 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0

03-20 17:46:02.202 22305 22305 E AndroidRuntime: 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)

03-20 17:46:02.202 22305 22305 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:308)

03-20 17:46:02.202 22305 22305 E AndroidRuntime: 	at com.sahdeepsingh.Bop.services.ServicePlayMusic.h(Unknown Source)

03-20 17:46:02.202 22305 22305 E AndroidRuntime: 	at com.sahdeepsingh.Bop.Activities.PlayerView.o(Unknown Source)

03-20 17:46:02.202 22305 22305 E AndroidRuntime: 	at com.sahdeepsingh.Bop.Activities.PlayerView$6.onClick(Unknown Source)

03-20 17:46:02.202 22305 22305 E AndroidRuntime: 	at android.view.View.performClick(View.java:5714)

03-20 17:46:02.202 22305 22305 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22589)

03-20 17:46:02.202 22305 22305 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

03-20 17:46:02.202 22305 22305 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

03-20 17:46:02.202 22305 22305 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

03-20 17:46:02.202 22305 22305 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

03-20 17:46:02.202 22305 22305 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

03-20 17:46:02.202 22305 22305 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

03-20 17:46:02.202 22305 22305 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by iamSahdeep** [comment]
Thanks @sagorahmed , It is known issue, I am working on it too. Thanks again.

**Comment by sagorahmed** [comment]
Good to know about it. Thanks, paji!!

**Comment by iamSahdeep** [comment]
@sagorahmed can you check the apk for this issue, if it is resolved or not. https://github.com/iamSahdeep/Bop/blob/master/buildApk/app-debug.apk

**Comment by sagorahmed** [comment]
Thanks for solving the issue. That issue is not occurring anymore. But #38 is still there to crash the app.

**Comment by iamSahdeep** [comment]
I will work on that too
