### ISSUE TITLE
The app freezes when I enable shuffle and try to play next track on an album with just one song in it 

### ISSUE THREAD

**Issue by HarryHeights** [iamSahdeep/Bop#37]
**Describe the bug**
I played a music album on the app which was having only one track in it. While the music was playing, I accessed the player's navigation control. I enabled shuffle; which would randomize the queue of the songs on the list. When I clicked the next button, the app froze and never got out of that state until I had to force close the app by clearing it out of my running apps. Even the navigation on my notification panel didn't work. However, the track continued to play. 

**To Reproduce**

- Play an album having only one track in it.
- Access the music player navigation page by clicking the musical note icon at the right side of the app.
- On the navigation page; change the playing mode to shuffle. (Just click on the two forward arrows just beneath the rotating disc). 
- After you have changed the mode to shuffle, click on next.
- See error.( The app freezes but the music continues to play)

**Expected behavior**
I expected that when I enable shuffle mode, and I tried to play the next song, the same song I was playing would repeat itself since it is the only song on the album. 

**Screen recording**
https://youtu.be/pT4HicrBUpY

**Test Environment:**
 - Device: Redmi Note 5 Pro
 - OS: Android 8.1
 - Software version: Bop music player v1.1.2

**Comment by iamSahdeep** [comment]
Sorry i was busy these 2 days. I am able to reproduce it to and will resolve it soon

**Comment by HarryHeights** [comment]
No qualms.

**Comment by iamSahdeep** [comment]
Hey @HarryHeights can you plz test this apk for both issues https://github.com/iamSahdeep/Bop/blob/master/buildApk/app-debug.apk

**Comment by HarryHeights** [comment]
Okay. Testing now.

**Comment by HarryHeights** [comment]
Both issues are opened are now fixed. Great job.
