### ISSUE TITLE
Bug found in Bop-MusicPlayer app ( Different options in the setting are not displayed in Secreen Rotate mode)

### ISSUE THREAD

**Issue by nasirshah1813** [iamSahdeep/Bop#43]
#### Project Information

* Repository: https://github.com/iamSahdeep/Bop

* Project Name:  	Bop - Music Player

* Publisher   : jeremymarch
 
#### Expected behavior
According to my knowledge As different types of settings appear in the portrait screen, all of them should appear in the Option Landscape mode as well.

#### Actual behavior
As I open the application  and click on the Settings button, after clicking the button on the Landscape mode mode, different options in the settings do not appear as you can see in the video.

#### How to reproduce
* [download](https://play.google.com/store/apps/details?id=com.sahdeepsingh.Bop&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1) app from f droid 
* and install and open the application
* click on the setting button 
* rotate the screen portrait to landscape 
* note the bug 
* Browser:   	Bop - Music Player
* Operating system: android version 8.0
 

#### Recording Of The Bug
https://www.youtube.com/watch?v=n3bMEE8gXAo
#### Proof of Work Done   
https://github.com/nasirshah1813

Submitted the [issue ](https://github.com/iamSahdeep/Bop/issues/43)on GitHub

**Comment by iamSahdeep** [comment]
I am able to reproduce the bug, Thanks for reporting. But you have accidentally put the wrong heading and project repository link in "Project Information" section.

**Comment by nasirshah1813** [comment]
sorry typing mistake sir
