### ISSUE TITLE
Bug on Theme 

### ISSUE THREAD

**Issue by darewealth** [iamSahdeep/Bop#44]
#### Expected behavior
The theme is meant to change the color of an application. I was expecting to see changes in color as  I change the color of the application theme. 

#### Actual behavior
When I tried to change the color, the changes do not have an effect. I tried it several times and it does not work. Rather if switches un-selected themes.

How to reproduce

* Launch the application and open the app

* Click on the 3 dot icon by the right at the top

* There will be a pop-up settings/quit

* Click on the ''Settings''

* Go to themes and click any color of your choice 

* Go back to settings and note the color didn't change.

App version:1.1.2 (11)

Operating system: Android 6.1

Device: Itel

Recording Of The Bug

https://youtu.be/aN953k1HVfk

**Comment by iamSahdeep** [comment]
Hello @darewealth thanks for reporting, I have reproduced the error. And for immediate change of theme,will required recreation of activity, which is causing issue #43 . So i need to find a workaround for both problems. Would take some time.

**Comment by iamSahdeep** [comment]
fixed in [v1.2.1](https://github.com/iamSahdeep/Bop/releases/tag/v1.2.1)
