### ISSUE TITLE
The app crashed when I tried to create a playlist from the Files menu by giving an already deleted playlist's name.

### ISSUE THREAD

**Issue by sagorahmed** [iamSahdeep/Bop#46]
**Describe the bug**
When I deleted a playlist and I tried to create a new one with the same name from the same directory of that deleted playlist's songs, then The app crashed for a couple of times.

**To Reproduce**
1. Go to the 'Files' menu.
2. Choose a folder of songs and open it (Remember the name of the folder).
3. Then click "PLAY ALL"
4. Click on ⋮ (Three dots/ Vertical ellipsis) at the right side of the song's number and click "Save Playlist".
5. Give a name and click on the "CREATE" button (Your playlist will be saved as your given name, remember that name).
6. Then open the "Playlist" menu.
7. Click on ⋮ (Three dots/ Vertical ellipsis) at the right side of your created playlist and delete it (Remember your playlist name).
8. Then try to create a new playlist by giving your deleted playlist name from your "step no: 2" folder.
9. See error.

**Expected behavior**
The users should be able to create the playlist by giving previously deleted playlist name from the same directory. 

**Recorded Video**
https://www.youtube.com/watch?v=w8l5kT1OncY

**Information**
 - Device: Samsung A5
 - OS: Android 6.0.1
 - App version: v1.2.1

**Logcat**
```
04-06 14:21:49.521 26582 26582 E AndroidRuntime: FATAL EXCEPTION: main

04-06 14:21:49.521 26582 26582 E AndroidRuntime: Process: com.sahdeepsingh.Bop, PID: 26582

04-06 14:21:49.521 26582 26582 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@d258238 is not valid; is your activity running?

04-06 14:21:49.521 26582 26582 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:894)

04-06 14:21:49.521 26582 26582 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:337)

04-06 14:21:49.521 26582 26582 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)

04-06 14:21:49.521 26582 26582 E AndroidRuntime: 	at android.app.Dialog.show(Dialog.java:505)

04-06 14:21:49.521 26582 26582 E AndroidRuntime: 	at com.sahdeepsingh.Bop.f.a.c(Unknown Source)

04-06 14:21:49.521 26582 26582 E AndroidRuntime: 	at com.sahdeepsingh.Bop.Activities.PlayingNowList$5.onClick(Unknown Source)

04-06 14:21:49.521 26582 26582 E AndroidRuntime: 	at android.view.View.performClick(View.java:5714)

04-06 14:21:49.521 26582 26582 E AndroidRuntime: 	at android.widget.TextView.performClick(TextView.java:10932)

04-06 14:21:49.521 26582 26582 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22589)

04-06 14:21:49.521 26582 26582 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

04-06 14:21:49.521 26582 26582 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

04-06 14:21:49.521 26582 26582 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

04-06 14:21:49.521 26582 26582 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

04-06 14:21:49.521 26582 26582 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

04-06 14:21:49.521 26582 26582 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
```

**Comment by iamSahdeep** [comment]
To show Progress dialogue I was using the getActivity for the context and sometimes getActivity is returning null. So, i have now saving context in onAttach method. Will soon add fix  in next release

**Comment by sagorahmed** [comment]
Good to see this issue solved.

**Comment by iamSahdeep** [comment]
fixed in v.1.2.2
