### ISSUE TITLE
Getting problem to share the songs

### ISSUE THREAD

**Issue by sagorahmed** [iamSahdeep/Bop#47]
**Describe the bug**
I am unable to share songs using this app. It has a feature called "Share" to share songs via other third parties/system software but it is not working to share. 

**To Reproduce**
1. Open the app.
2. Go to the side menu and Open "Playlist".
3. Choose a playlist and click on ⋮ (Three dots/ Vertical ellipsis) at the side of the playlist.
4. Then click "Show files".
5. Choose a song and click on three dots at the side of the song.
6. Click "Share" and choose an app to share.
7. See error.

**Expected behavior**
The users should be able to share the songs without getting any trouble.

**Information):**
 - Device: Samsung A5
 - OS: Android 6.0.1
 - App Version: v1.2.1

**Screenshots**
![gif_image4 1](https://user-images.githubusercontent.com/33980813/55859901-dea2a800-5b94-11e9-8f88-94eb2cbd084e.gif)

**Comment by iamSahdeep** [comment]
Yeah, i too can't share it. Will look for solution soon. Currently i am busy with my college and would work again on issues left soon. Thanks

**Comment by sagorahmed** [comment]
Thanks, @iamSahdeep for your fast response.

**Comment by iamSahdeep** [comment]
fixed in v1.2.2
