### ISSUE TITLE
Add Two Features in Bop - Music Player ( Black List) and ( Networks Stream ) 

### ISSUE THREAD

**Issue by nasirshah1813** [iamSahdeep/Bop#48]
# Repository
https://github.com/iamSahdeep/Bop

# Components

Bop - Music Player is an open source application. the application is lightweight in this application you can play all types of media mp3, FLAC, midi, wav, aac files, and other audio file formats.there are many features in this application An Equalizer  Music visualizer Lots of color themes  Searching Capability available in this application the simple design and colors showing of Developer experience.

# Proposals
 
there are  many features in this application  but I like to suggest some feature in this application
 the feature is.

 #### 1- Black List

The major Function of Blacklist is the contents of the blacklisted folder is hidden from the music library. Sometimes you have an important  Audio recording file  in your music library and you want to cannot play this imported files in Bop - Music Player with the help of Black List you can hide your imported file  from the music library 

#### 2- Networks Stream

Networks Stream  is a Philadelphia-based new media company with the help of this feature you can listen to the songs online just copy your songs link from any websites and put in the network stream box. there are many Streaming Free Music Sites  below 

Google Play Music
iHeartRadio
SoundCloud
SHOUTcast
AccuRadio
Last.fm

# Mockups/ Examples

when we add the Blacklist features 

![1.png](https://ipfs.busy.org/ipfs/QmPdcsmgK1BtzArLTdxszr9S4DPsREYFVmGgJP86q7tnKj)

when we click on the   Blacklist features 
![2.png](https://ipfs.busy.org/ipfs/QmZXdrc7V65Ns7dQxS8d2RGLD3etVsiZnJP1NhJq7jZdQu)

when we add Networks Stream Feature 

![3.png](https://ipfs.busy.org/ipfs/QmUMzC4vgjywhVwcLYkBR28xNBWiX8iKqPCLs3YhyxtCsd)

when we click on the   Networks Stream Feature 

![4.png](https://ipfs.busy.org/ipfs/Qmccfiava6JjmF2f5NAB214LMLTNJGgJrDWfKVATfJqtXR)

# Benefits

With the help of the Black List, you can hide your important music files from the library.
you can listen to brand new songs with help of  Networks Stream feature 

# GitHub Account
https://github.com/nasirshah1813

**Comment by iamSahdeep** [comment]
@nasirshah1813 Hi, thanks for these feature requests. Blocking folders LGTM but network stream wouldn't be possible. I want to Keep Bop completely offline. Would work on it soon as possible.

**Comment by nasirshah1813** [comment]
thanks u sir
