### ISSUE TITLE
unable to update v1.2 to 1.2.1

### ISSUE THREAD

**Issue by sagorahmed** [iamSahdeep/Bop#53]
**Describe the bug**
On the PlayStore, Bop music player v1.2 is available. But on the Github release page, the version of it is 1.2.1. 
The installed app version on my phone is v1.2. This is why when I am trying to update it by downloading the latest version v1.2.1 from Github release page, then the installation process is not finished successfully. 

**To Reproduce**
1. Install v1.2 from <a href="https://play.google.com/store/apps/details?id=com.sahdeepsingh.Bop">Play Store</a>.
2. Then download the v1.2.1 from GitHub release page and try to install it as an update.
3. Notice the error.

**Expected behavior**
The users should be able to update an older version without any trouble.

**Information:**
 - OS: Android 6.0.1
 - Version 1.2.1

I think this issue is occurring because of v1.2.1. But you can avoid it by uninstalling the v1.2 and installing the v1.2.1 later on.

**Comment by iamSahdeep** [comment]
Hey @sagorahmed thanks for submitting issue. The issue is because of the fact that 1.2 is the stable version on play store while github releases are unstable.
