### ISSUE TITLE
Add online music feature.

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [iamSahdeep/Bop#56]
#### Proposal:
My suggestion is to add *Online Music* feature in this Bop-music player.
#### Mockups:
* When we open the music player, its looks like this:
![IMG_20190515_142332](https://user-images.githubusercontent.com/37048415/57762402-131dfc80-771d-11e9-97bc-d7a0bc0cdc92.jpg)
* After that, click on the 3 lines on top left corner, it looks like this:
![PicsArt_05-15-02 19 42](https://user-images.githubusercontent.com/37048415/57762484-36e14280-771d-11e9-96a8-00fb56e77bb2.png)
* Then after clicking on the Highlighted portion, it shows ***Bop-music player***.
On that place it also must contain ***Online music, like this:***.
![PicsArt_05-15-02 21 15](https://user-images.githubusercontent.com/37048415/57762606-6e4fef00-771d-11e9-85a7-1b1b547ccf4a.png)

#### Benefits:
As we all know that the music has become one's part of a life, some people listen music too much. Firstly they had to search the latest music and then they have to download. After downloading they can see that very song in their music player. It looks too much time consuming.
So benefits of my suggestion are that; a user don't have to search the latest music, in other words latest music will appear automatically in **Online Music**. 
Another benefit is that a user have no need of downloading that very song(s), which will save his time as well as internet data too.

**Comment by iamSahdeep** [comment]
Hey @PeerzadaZeeshan  Thanks for suggestion. however I am gonna keep it for local songs only. No online streaming at least for now.
