### ISSUE TITLE
Removing a song from playlist didn't remove it.

### ISSUE THREAD

**Issue by Xeeshuu** [iamSahdeep/Bop#59]
After creating a playlist of songs, when i tried to remove a song from that playlist, it gets removed on that moment but when i recheck it, it is still in the playlist.
**Screenshot/Video**
![20190609_133052](https://user-images.githubusercontent.com/37048348/59156595-4dc84a00-8abb-11e9-9e51-6fc106de47b7.gif)
**Steps to produce:*
Open the app.
Create a playlist of songs.
Go to that playlist.
Remove the song from it.
Recheck playlist to produce the bug.

**Comment by iamSahdeep** [comment]
Hi @Xeeshuu you might be using older version or the release one. You might want to try beta release i.e, v1.2.1. Also in video, you are removing song from the current playlist not actual playlist.You can download pre release from github or playstore beta program  which have song removing feature from playlist

**Comment by Xeeshuu** [comment]
> Hi @Xeeshuu you might be using older version or the release one. You might want to try beta release i.e, v1.2.1. Also in video, you are removing song from the current playlist not actual playlist.You can download pre release from github or playstore beta program which have song removing feature from playlist

Can you provide me a link to download.
